project:
  type: website
  output-dir: site
  render:
  - "notebooks/*"
  - about.qmd
  - index.qmd

resources:
  - assets/**
execute:
  enabled: false
  # freeze: auto

website:
  title: "Prix du logement vs offre de transport"
  
  search: false
  navbar:
    logo-href: /notebooks/main.ipynb
    brand:
      - text: Prix du logement vs offre de transport
        href: notebooks/main.ipynb
    left:
      - text: Analyse
        href: notebooks/main.ipynb
      - text: Traitement DVF
        href: notebooks/dvf.ipynb
      - text: Traitement IDFM
        href: notebooks/idfm.ipynb
      - text: About
        href: about.qmd
    right:
      - href: "https://github.com/gaybrice/projet-python-ds"
        icon: github

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true